# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: "SpacyTokenizer"
  - name: "SpacyEntityExtractor"
    model: "en_core_web_sm"  # Use a smaller model

policies:
  - name: "MemoizationPolicy"
  - name: "KerasPolicy"

